### ISSUE TITLE
SSL library needs to be upgraded

### ISSUE THREAD

**Issue by cchriste** [sci-visus/OpenVisus#47] opened 2019-02-28 17:33 UTC
The current SSL is too old a version for some servers (ex: anything at a national lab). We need to link to a newer version, so probably adding the latest libssl to OpenVisus like we do with many other libs. 

You can test by trying to open:
`https://aims2.llnl.gov/visus/mod_visus?dataset=1_BlueMarble`

**Comment by cchriste** [comment] 2019-03-16 04:56
This is needed for testing and demonstration of our CDMS server at LLNL.

`$ ./visus.command info "https://aims2.llnl.gov/visus/mod_visus?action=readdataset&dataset=nature_2007_aer1_hourly"`

currently fails with
`error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version`

**Comment by scrgiorgio** [comment] 2019-03-17 15:41
Hi Cameron.

please try this branch:

https://github.com/sci-visus/OpenVisus/tree/DroppingOpenSSL

it will use LibreSSL instead of OpenSSL. it should support TLS v 1.2.
Let me know.

PS check from CMake logs if it's really using internal LibresSSL and not an
external OpenSSL

**Comment by cchriste** [comment] 2019-03-18 04:52
Thanks, Giorgio,
I tried it from my OpenSUSE machine and it worked.

**Comment by scrgiorgio** [comment] 2019-03-18 08:05
I removed the Internal/OpenSSL and added Internal/libreSSL.
It's working a lot better now.
Cameron, if the problem is solved please close this issue

**Comment by scrgiorgio** [comment] 2019-03-18 13:27
solved

**Closed by scrgiorgio** 2019-03-18 13:27 UTC
